export {Header} from './Header'
export {Sidebar} from './Sidebar'
export {Main} from './Main'
export {Category} from './Category'
export {MainPosts} from './MainPosts'
// export {MainPosts} from './MainPosts'
export {NavCategory} from './NavCategory'